Dec  1 11:03:34 node<<1>> gps: : time increase in gps of 1322737415 s.
Dec  1 11:03:38 node<<2>> acquire2: : fast data recording off
Dec  1 11:03:38 node<<2>> acquire2: : integrated data recording off
Dec  1 15:59:17 node<<1>> gps: : time increase in gps of 1322753589 s.
Dec  1 15:33:11 node<<2>> acquire2: : fast data recording off
Dec  1 15:33:11 node<<2>> acquire2: : integrated data recording off
Dec  1 11:22:53 node<<1>> gps: : time increase in gps of 1354360975 s.
Dec  1 11:22:58 node<<2>> acquire2: : fast data recording off
Dec  1 11:22:58 node<<2>> acquire2: : integrated data recording off
Dec  2 10:52:55 node<<1>> gps: : time increase in gps of 1322823177 s.
Dec  2 10:53:00 node<<2>> acquire2: : fast data recording off
Dec  2 10:53:00 node<<2>> acquire2: : integrated data recording off
Dec  2 11:11:30 node<<1>> gps: : time increase in gps of 1354446691 s.
Dec  2 11:11:34 node<<2>> acquire2: : fast data recording off
Dec  2 11:11:34 node<<2>> acquire2: : integrated data recording off
Dec  3 10:54:39 node<<1>> gps: : time increase in gps of 1322909680 s.
Dec  3 10:54:43 node<<2>> acquire2: : fast data recording off
Dec  3 10:54:43 node<<2>> acquire2: : integrated data recording off
Dec  3 15:11:16 node<<1>> gps: : time increase in gps of 1322923507 s.
Dec  3 14:45:10 node<<2>> acquire2: : fast data recording off
Dec  3 14:45:10 node<<2>> acquire2: : integrated data recording off
Dec  3 11:28:46 node<<1>> gps: : time increase in gps of 1354534127 s.
Dec  3 11:28:50 node<<2>> acquire2: : fast data recording off
Dec  3 11:28:50 node<<2>> acquire2: : integrated data recording off
Dec  3 16:00:04 node<<1>> gps: : nmea code too short with -1 chars.
Dec  3 16:00:05 node<<1>> gps: : time increase in gps of 0 s.
Dec  3 16:00:05 node<<1>> gps: : nmea code too short with 36 chars.
Dec  3 16:00:03 node<<1>> gps: : time increase in gps of 2 s.
Dec  3 17:53:44 node<<1>> gps: : time increase in gps of 1354555433 s.
Dec  3 17:23:55 node<<2>> acquire2: : fast data recording off
Dec  3 17:23:55 node<<2>> acquire2: : integrated data recording off
Dec  3 10:54:39 node<<1>> gps: : time increase in gps of 1322909680 s.
Dec  3 10:54:43 node<<2>> acquire2: : fast data recording off
Dec  3 10:54:43 node<<2>> acquire2: : integrated data recording off
Dec  3 15:11:16 node<<1>> gps: : time increase in gps of 1322923507 s.
Dec  3 14:45:10 node<<2>> acquire2: : fast data recording off
Dec  3 14:45:10 node<<2>> acquire2: : integrated data recording off
Dec  3 11:28:46 node<<1>> gps: : time increase in gps of 1354534127 s.
Dec  3 11:28:50 node<<2>> acquire2: : fast data recording off
Dec  3 11:28:50 node<<2>> acquire2: : integrated data recording off
Dec  3 16:00:04 node<<1>> gps: : nmea code too short with -1 chars.
Dec  3 16:00:05 node<<1>> gps: : time increase in gps of 0 s.
Dec  3 16:00:05 node<<1>> gps: : nmea code too short with 36 chars.
Dec  3 16:00:03 node<<1>> gps: : time increase in gps of 2 s.
Dec  3 17:53:44 node<<1>> gps: : time increase in gps of 1354555433 s.
Dec  3 17:23:55 node<<2>> acquire2: : fast data recording off
Dec  3 17:23:55 node<<2>> acquire2: : integrated data recording off
Dec  4 10:51:51 node<<1>> gps: : time increase in gps of 1322995912 s.
Dec  4 10:51:55 node<<2>> acquire2: : fast data recording off
Dec  4 10:51:55 node<<2>> acquire2: : integrated data recording off
Dec  4 18:52:05 node<<1>> gps: : time increase in gps of 1323024727 s.
Dec  4 18:52:10 node<<2>> acquire2: : fast data recording off
Dec  4 18:52:10 node<<2>> acquire2: : integrated data recording off
Dec  4 19:13:07 node<<1>> gps: : time increase in gps of 1323025988 s.
Dec  4 19:13:11 node<<2>> acquire2: : fast data recording off
Dec  4 19:13:11 node<<2>> acquire2: : integrated data recording off
Dec  4 11:42:56 node<<1>> gps: : time increase in gps of 1354619585 s.
Dec  4 11:13:07 node<<2>> acquire2: : fast data recording off
Dec  4 11:13:07 node<<2>> acquire2: : integrated data recording off
Dec  5 10:50:55 node<<1>> gps: : time increase in gps of 1323082256 s.
Dec  5 10:50:59 node<<2>> acquire2: : fast data recording off
Dec  5 10:50:59 node<<2>> acquire2: : integrated data recording off
Dec  5 18:27:28 node<<1>> gps: : time increase in gps of 1323108078 s.
Dec  5 18:01:21 node<<2>> acquire2: : fast data recording off
Dec  5 18:01:21 node<<2>> acquire2: : integrated data recording off
Dec  5 11:24:32 node<<1>> gps: : time increase in gps of 1354706673 s.
Dec  5 11:24:36 node<<2>> acquire2: : fast data recording off
Dec  5 11:24:36 node<<2>> acquire2: : integrated data recording off
Dec  5 11:29:38 node<<1>> gps: : time increase in gps of 1354706979 s.
Dec  5 11:29:42 node<<2>> acquire2: : fast data recording off
Dec  5 11:29:42 node<<2>> acquire2: : integrated data recording off
Dec  5 15:16:13 node<<1>> gps: : time increase in gps of 1354718782 s.
Dec  5 14:46:24 node<<2>> acquire2: : fast data recording off
Dec  5 14:46:24 node<<2>> acquire2: : integrated data recording off
Dec  5 18:57:56 node<<1>> gps: : nmea code too short with 28 chars.
Dec  5 18:57:56 node<<1>> gps: : invalid gps time
Dec  5 18:57:57 node<<1>> gps: : time increase in gps of 1354733879 s.
Dec  5 18:58:01 node<<2>> acquire2: : fast data recording off
Dec  5 18:58:01 node<<2>> acquire2: : integrated data recording off
Dec  6 10:53:05 node<<1>> gps: : time increase in gps of 1323168787 s.
Dec  6 10:53:10 node<<2>> acquire2: : fast data recording off
Dec  6 10:53:10 node<<2>> acquire2: : integrated data recording off
Dec  6 11:24:24 node<<1>> gps: : time increase in gps of 1354793066 s.
Dec  6 11:24:29 node<<2>> acquire2: : fast data recording off
Dec  6 11:24:29 node<<2>> acquire2: : integrated data recording off
Dec  6 17:29:01 node<<1>> gps: : time increase in gps of 1354813150 s.
Dec  6 16:59:12 node<<2>> acquire2: : fast data recording off
Dec  6 16:59:12 node<<2>> acquire2: : integrated data recording off
Dec  6 22:42:42 node<<1>> gps: : Unable to set clock on node 2. Resource temporarily unavailable
Dec  6 22:42:43 node<<1>> gps: : Unable to read clock on node 2. Resource temporarily unavailable
Dec  6 22:42:52 node<<1>> gps: : Unable to set clock on node 2. Resource temporarily unavailableInterrupted function call
Dec  7 10:44:30 node<<1>> gps: : time increase in gps of 1323254671 s.
Dec  7 10:44:34 node<<2>> acquire2: : fast data recording off
Dec  7 10:44:34 node<<2>> acquire2: : integrated data recording off
Dec  7 12:11:17 node<<1>> gps: : time increase in gps of 1354880485 s.
Dec  7 11:41:27 node<<2>> acquire2: : fast data recording off
Dec  7 11:41:27 node<<2>> acquire2: : integrated data recording off
Dec  7 22:23:44 node<<1>> gps: : time increase in gps of 1354917232 s.
Dec  7 21:53:54 node<<2>> acquire2: : fast data recording off
Dec  7 21:53:54 node<<2>> acquire2: : integrated data recording off
Dec  8 11:18:43 node<<1>> gps: : time increase in gps of 1323343125 s.
Dec  8 11:18:48 node<<2>> acquire2: : fast data recording off
Dec  8 11:18:48 node<<2>> acquire2: : integrated data recording off
Dec  8 11:22:16 node<<1>> gps: : time increase in gps of 1323343337 s.
Dec  8 11:22:20 node<<2>> acquire2: : fast data recording off
Dec  8 11:22:20 node<<2>> acquire2: : integrated data recording off
Dec  8 14:51:43 node<<1>> gps: : time increase in gps of 1323354331 s.
Dec  8 14:25:33 node<<2>> acquire2: : fast data recording off
Dec  8 14:25:33 node<<2>> acquire2: : integrated data recording off
Dec  8 18:11:07 node<<1>> gps: : time increase in gps of 1323366295 s.
Dec  8 17:44:57 node<<2>> acquire2: : fast data recording off
Dec  8 17:44:57 node<<2>> acquire2: : integrated data recording off
Dec  8 11:33:12 node<<1>> gps: : nmea code too short with 6 chars.
Dec  8 11:33:12 node<<1>> gps: : invalid gps time
Dec  8 11:33:13 node<<1>> gps: : time increase in gps of 1354966395 s.
Dec  8 11:33:17 node<<2>> acquire2: : fast data recording off
Dec  8 11:33:17 node<<2>> acquire2: : integrated data recording off
Dec  8 21:23:38 node<<1>> gps: : time increase in gps of 1355000026 s.
Dec  8 20:53:48 node<<2>> acquire2: : fast data recording off
Dec  8 20:53:48 node<<2>> acquire2: : integrated data recording off
Dec  9 11:28:55 node<<1>> gps: : time increase in gps of 1323430136 s.
Dec  9 11:28:59 node<<2>> acquire2: : fast data recording off
Dec  9 11:28:59 node<<2>> acquire2: : integrated data recording off
Dec  9 11:02:07 node<<1>> gps: : time increase in gps of 1355050929 s.
Dec  9 11:02:12 node<<2>> acquire2: : fast data recording off
Dec  9 11:02:12 node<<2>> acquire2: : integrated data recording off
Dec  9 14:43:40 node<<1>> gps: : time increase in gps of 1355062427 s.
Dec  9 14:13:49 node<<2>> acquire2: : fast data recording off
Dec  9 14:13:49 node<<2>> acquire2: : integrated data recording off
Dec  9 19:48:53 node<<1>> gps: : time increase in gps of 1355080740 s.
Dec  9 19:19:02 node<<2>> acquire2: : fast data recording off
Dec  9 19:19:02 node<<2>> acquire2: : integrated data recording off
Dec  9 22:26:52 node<<1>> gps: : time increase in gps of 1355090220 s.
Dec  9 21:57:02 node<<2>> acquire2: : fast data recording off
Dec  9 21:57:02 node<<2>> acquire2: : integrated data recording off
Dec  8 11:18:43 node<<1>> gps: : time increase in gps of 1323343125 s.
Dec  8 11:18:48 node<<2>> acquire2: : fast data recording off
Dec  8 11:18:48 node<<2>> acquire2: : integrated data recording off
Dec  8 11:22:16 node<<1>> gps: : time increase in gps of 1323343337 s.
Dec  8 11:22:20 node<<2>> acquire2: : fast data recording off
Dec  8 11:22:20 node<<2>> acquire2: : integrated data recording off
Dec  8 14:51:43 node<<1>> gps: : time increase in gps of 1323354331 s.
Dec  8 14:25:33 node<<2>> acquire2: : fast data recording off
Dec  8 14:25:33 node<<2>> acquire2: : integrated data recording off
Dec  8 18:11:07 node<<1>> gps: : time increase in gps of 1323366295 s.
Dec  8 17:44:57 node<<2>> acquire2: : fast data recording off
Dec  8 17:44:57 node<<2>> acquire2: : integrated data recording off
Dec  8 11:33:12 node<<1>> gps: : nmea code too short with 6 chars.
Dec  8 11:33:12 node<<1>> gps: : invalid gps time
Dec  8 11:33:13 node<<1>> gps: : time increase in gps of 1354966395 s.
Dec  8 11:33:17 node<<2>> acquire2: : fast data recording off
Dec  8 11:33:17 node<<2>> acquire2: : integrated data recording off
Dec  8 21:23:38 node<<1>> gps: : time increase in gps of 1355000026 s.
Dec  8 20:53:48 node<<2>> acquire2: : fast data recording off
Dec  8 20:53:48 node<<2>> acquire2: : integrated data recording off
Dec  8 11:18:43 node<<1>> gps: : time increase in gps of 1323343125 s.
Dec  8 11:18:48 node<<2>> acquire2: : fast data recording off
Dec  8 11:18:48 node<<2>> acquire2: : integrated data recording off
Dec  8 11:22:16 node<<1>> gps: : time increase in gps of 1323343337 s.
Dec  8 11:22:20 node<<2>> acquire2: : fast data recording off
Dec  8 11:22:20 node<<2>> acquire2: : integrated data recording off
Dec  8 14:51:43 node<<1>> gps: : time increase in gps of 1323354331 s.
Dec  8 14:25:33 node<<2>> acquire2: : fast data recording off
Dec  8 14:25:33 node<<2>> acquire2: : integrated data recording off
Dec  8 18:11:07 node<<1>> gps: : time increase in gps of 1323366295 s.
Dec  8 17:44:57 node<<2>> acquire2: : fast data recording off
Dec  8 17:44:57 node<<2>> acquire2: : integrated data recording off
Dec  8 11:33:12 node<<1>> gps: : nmea code too short with 6 chars.
Dec  8 11:33:12 node<<1>> gps: : invalid gps time
Dec  8 11:33:13 node<<1>> gps: : time increase in gps of 1354966395 s.
Dec  8 11:33:17 node<<2>> acquire2: : fast data recording off
Dec  8 11:33:17 node<<2>> acquire2: : integrated data recording off
Dec  8 21:23:38 node<<1>> gps: : time increase in gps of 1355000026 s.
Dec  8 20:53:48 node<<2>> acquire2: : fast data recording off
Dec  8 20:53:48 node<<2>> acquire2: : integrated data recording off
Dec  9 11:28:55 node<<1>> gps: : time increase in gps of 1323430136 s.
Dec  9 11:28:59 node<<2>> acquire2: : fast data recording off
Dec  9 11:28:59 node<<2>> acquire2: : integrated data recording off
Dec  9 11:02:07 node<<1>> gps: : time increase in gps of 1355050929 s.
Dec  9 11:02:12 node<<2>> acquire2: : fast data recording off
Dec  9 11:02:12 node<<2>> acquire2: : integrated data recording off
Dec  9 14:43:40 node<<1>> gps: : time increase in gps of 1355062427 s.
Dec  9 14:13:49 node<<2>> acquire2: : fast data recording off
Dec  9 14:13:49 node<<2>> acquire2: : integrated data recording off
Dec  9 19:48:53 node<<1>> gps: : time increase in gps of 1355080740 s.
Dec  9 19:19:02 node<<2>> acquire2: : fast data recording off
Dec  9 19:19:02 node<<2>> acquire2: : integrated data recording off
Dec  9 22:26:52 node<<1>> gps: : time increase in gps of 1355090220 s.
Dec  9 21:57:02 node<<2>> acquire2: : fast data recording off
Dec  9 21:57:02 node<<2>> acquire2: : integrated data recording off
Dec 10 11:34:46 node<<1>> gps: : nmea code too short with 21 chars.
Dec 10 11:34:46 node<<1>> gps: : invalid gps time
Dec 10 11:34:47 node<<1>> gps: : time increase in gps of 1323516888 s.
Dec 10 11:34:50 node<<2>> acquire2: : fast data recording off
Dec 10 11:34:50 node<<2>> acquire2: : integrated data recording off
Dec 10 11:16:00 node<<1>> gps: : time increase in gps of 1355138162 s.
Dec 10 11:16:05 node<<2>> acquire2: : fast data recording off
Dec 10 11:16:05 node<<2>> acquire2: : integrated data recording off
Dec 10 15:14:53 node<<1>> gps: : time increase in gps of 1355150701 s.
Dec 10 14:45:03 node<<2>> acquire2: : fast data recording off
Dec 10 14:45:03 node<<2>> acquire2: : integrated data recording off
Dec 10 17:46:38 node<<1>> gps: : time increase in gps of 1355159805 s.
Dec 10 17:16:47 node<<2>> acquire2: : fast data recording off
Dec 10 17:16:47 node<<2>> acquire2: : integrated data recording off
Dec  5 10:50:55 node<<1>> gps: : time increase in gps of 1323082256 s.
Dec  5 10:50:59 node<<2>> acquire2: : fast data recording off
Dec  5 10:50:59 node<<2>> acquire2: : integrated data recording off
Dec  5 18:27:28 node<<1>> gps: : time increase in gps of 1323108078 s.
Dec  5 18:01:21 node<<2>> acquire2: : fast data recording off
Dec  5 18:01:21 node<<2>> acquire2: : integrated data recording off
Dec  5 11:24:32 node<<1>> gps: : time increase in gps of 1354706673 s.
Dec  5 11:24:36 node<<2>> acquire2: : fast data recording off
Dec  5 11:24:36 node<<2>> acquire2: : integrated data recording off
Dec  5 11:29:38 node<<1>> gps: : time increase in gps of 1354706979 s.
Dec  5 11:29:42 node<<2>> acquire2: : fast data recording off
Dec  5 11:29:42 node<<2>> acquire2: : integrated data recording off
Dec  5 15:16:13 node<<1>> gps: : time increase in gps of 1354718782 s.
Dec  5 14:46:24 node<<2>> acquire2: : fast data recording off
Dec  5 14:46:24 node<<2>> acquire2: : integrated data recording off
Dec  5 18:57:56 node<<1>> gps: : nmea code too short with 28 chars.
Dec  5 18:57:56 node<<1>> gps: : invalid gps time
Dec  5 18:57:57 node<<1>> gps: : time increase in gps of 1354733879 s.
Dec  5 18:58:01 node<<2>> acquire2: : fast data recording off
Dec  5 18:58:01 node<<2>> acquire2: : integrated data recording off
Dec 11 11:30:19 node<<1>> gps: : time increase in gps of 1323603020 s.
Dec 11 11:30:23 node<<2>> acquire2: : fast data recording off
Dec 11 11:30:23 node<<2>> acquire2: : integrated data recording off
Dec 11 14:00:06 node<<1>> gps: : nmea code too short with -1 chars.
Dec 11 14:00:06 node<<1>> gps: : time increase in gps of 0 s.
Dec 11 14:00:06 node<<1>> gps: : nmea code too short with 43 chars.
Dec 11 14:00:04 node<<1>> gps: : time increase in gps of 2 s.
Dec 11 11:07:52 node<<1>> gps: : time increase in gps of 1355224073 s.
Dec 11 11:07:56 node<<2>> acquire2: : fast data recording off
Dec 11 11:07:56 node<<2>> acquire2: : integrated data recording off
Dec 12 11:34:43 node<<1>> gps: : time increase in gps of 1323689684 s.
Dec 12 11:34:47 node<<2>> acquire2: : fast data recording off
Dec 12 11:34:47 node<<2>> acquire2: : integrated data recording off
Dec 12 11:19:57 node<<1>> gps: : time increase in gps of 1355311198 s.
Dec 12 11:20:01 node<<2>> acquire2: : fast data recording off
Dec 12 11:20:01 node<<2>> acquire2: : integrated data recording off
Dec 12 22:27:09 node<<1>> gps: : nmea code too short with 48 chars.
Dec 12 22:27:09 node<<1>> gps: : invalid gps time
Dec 12 22:27:10 node<<1>> gps: : time increase in gps of 1355351231 s.
Dec 12 22:27:13 node<<2>> acquire2: : fast data recording off
Dec 12 22:27:13 node<<2>> acquire2: : integrated data recording off
Dec 13 11:01:01 node<<1>> gps: : time increase in gps of 1323774063 s.
Dec 13 11:01:06 node<<2>> acquire2: : fast data recording off
Dec 13 11:01:06 node<<2>> acquire2: : integrated data recording off
Dec 13 15:16:24 node<<1>> gps: : time increase in gps of 1323787809 s.
Dec 13 14:50:11 node<<2>> acquire2: : fast data recording off
Dec 13 14:50:11 node<<2>> acquire2: : integrated data recording off
Dec 13 19:30:56 node<<1>> gps: : time increase in gps of 1323803081 s.
Dec 13 19:04:43 node<<2>> acquire2: : fast data recording off
Dec 13 19:04:43 node<<2>> acquire2: : integrated data recording off
Dec 13 13:51:50 node<<1>> gps: : time increase in gps of 1355406712 s.
Dec 13 13:51:55 node<<2>> acquire2: : fast data recording off
Dec 13 13:51:55 node<<2>> acquire2: : integrated data recording off
Dec 13 14:47:23 node<<1>> gps: : time increase in gps of 1355410044 s.
Dec 13 14:47:27 node<<2>> acquire2: : fast data recording off
Dec 13 14:47:27 node<<2>> acquire2: : integrated data recording off
Dec 13 15:27:04 node<<1>> gps: : nmea code too short with 12 chars.
Dec 13 15:27:04 node<<1>> gps: : invalid gps time
Dec 13 15:27:05 node<<1>> gps: : time increase in gps of 1355412427 s.
Dec 13 15:27:09 node<<2>> acquire2: : fast data recording off
Dec 13 15:27:09 node<<2>> acquire2: : integrated data recording off
Dec 13 22:29:37 node<<1>> gps: : time increase in gps of 1355437779 s.
Dec 13 22:29:42 node<<2>> acquire2: : fast data recording off
Dec 13 22:29:42 node<<2>> acquire2: : integrated data recording off
Dec 13 23:02:16 node<<1>> gps: : time increase in gps of 1355437944 s.
Dec 13 22:32:26 node<<2>> acquire2: : fast data recording off
Dec 13 22:32:26 node<<2>> acquire2: : integrated data recording off
Dec 13 22:33:13 node<<1>> gps: : time increase in gps of 1355437995 s.
Dec 13 22:33:18 node<<2>> acquire2: : fast data recording off
Dec 13 22:33:18 node<<2>> acquire2: : integrated data recording off
Dec 13 22:40:07 node<<1>> gps: : time increase in gps of 1355438409 s.
Dec 13 22:40:12 node<<2>> acquire2: : fast data recording off
Dec 13 22:40:12 node<<2>> acquire2: : integrated data recording off
Dec 14 10:15:40 node<<1>> gps: : time increase in gps of 1323857741 s.
Dec 14 10:15:44 node<<2>> acquire2: : fast data recording off
Dec 14 10:15:44 node<<2>> acquire2: : integrated data recording off
Dec 14 11:35:50 node<<1>> gps: : time increase in gps of 1323860975 s.
Dec 14 11:09:37 node<<2>> acquire2: : fast data recording off
Dec 14 11:09:37 node<<2>> acquire2: : integrated data recording off
Dec 14 19:48:32 node<<1>> gps: : time increase in gps of 1323890537 s.
Dec 14 19:22:19 node<<2>> acquire2: : fast data recording off
Dec 14 19:22:19 node<<2>> acquire2: : integrated data recording off
Dec 14 20:00:29 node<<1>> gps: : time increase in gps of 1323892831 s.
Dec 14 20:00:34 node<<2>> acquire2: : fast data recording off
Dec 14 20:00:34 node<<2>> acquire2: : integrated data recording off
Dec 14 20:18:46 node<<1>> gps: : time increase in gps of 1323893927 s.
Dec 14 20:18:50 node<<2>> acquire2: : fast data recording off
Dec 14 20:18:50 node<<2>> acquire2: : integrated data recording off
Dec 14 02:12:50 node<<1>> gps: : time increase in gps of 1355451172 s.
Dec 14 02:12:55 node<<2>> acquire2: : fast data recording off
Dec 14 02:12:55 node<<2>> acquire2: : integrated data recording off
Dec 14 11:35:26 node<<1>> gps: : time increase in gps of 1355484928 s.
Dec 14 11:35:31 node<<2>> acquire2: : fast data recording off
Dec 14 11:35:31 node<<2>> acquire2: : integrated data recording off
Dec 14 12:00:05 node<<1>> gps: : nmea code too short with -1 chars.
Dec 14 12:00:05 node<<1>> gps: : time increase in gps of 0 s.
Dec 14 12:47:41 node<<1>> gps: : time increase in gps of 1355489263 s.
Dec 14 12:47:46 node<<2>> acquire2: : fast data recording off
Dec 14 12:47:46 node<<2>> acquire2: : integrated data recording off
Dec 14 12:48:33 node<<1>> gps: : time increase in gps of 1355489315 s.
Dec 14 12:48:38 node<<2>> acquire2: : fast data recording off
Dec 14 12:48:38 node<<2>> acquire2: : integrated data recording off
Dec 14 17:11:42 node<<1>> gps: : time increase in gps of 1355503309 s.
Dec 14 16:41:51 node<<2>> acquire2: : fast data recording off
Dec 14 16:41:51 node<<2>> acquire2: : integrated data recording off
Dec 27 03:15:13 node<<2>> acquire2: : fast data recording off
Dec 27 03:15:13 node<<2>> acquire2: : integrated data recording off
Dec 27 03:16:35 node<<1>> gps: : time increase in gps of 1356578197 s.
Dec 27 03:16:40 node<<2>> acquire2: : fast data recording off
Dec 27 03:16:40 node<<2>> acquire2: : integrated data recording off
Dec 27 12:22:04 node<<1>> gps: : time increase in gps of 1356610925 s.
Dec 27 12:22:08 node<<2>> acquire2: : fast data recording off
Dec 27 12:22:08 node<<2>> acquire2: : integrated data recording off
Dec 21 19:30:29 node<<2>> acquire2: : fast data recording off
Dec 21 19:30:29 node<<2>> acquire2: : integrated data recording off
Dec 21 20:31:09 node<<2>> acquire2: : fast data recording off
Dec 21 20:31:09 node<<2>> acquire2: : integrated data recording off
Dec 21 20:34:04 node<<2>> acquire2: : fast data recording off
Dec 21 20:34:04 node<<2>> acquire2: : integrated data recording off
Dec 21 20:34:08 node<<1>> gps: : Unable to set clock on node 2. Resource temporarily unavailable
Dec 21 20:34:31 node<<1>> gps: : Unable to set clock on node 2. Resource temporarily unavailableInterrupted function call
Dec 21 20:34:10 node<<1>> gps: : sys_time(node2)-time(gps) = 7.491568 ms.
Dec 21 20:35:11 node<<1>> gps: : time increase in gps of 1356122135 s.
Dec 21 20:35:38 node<<2>> acquire2: : fast data recording off
Dec 21 20:35:38 node<<2>> acquire2: : integrated data recording off
Dec 22 11:45:10 node<<2>> acquire2: : fast data recording off
Dec 22 11:45:10 node<<2>> acquire2: : integrated data recording off
Dec 22 11:45:18 node<<1>> gps: : Unable to set clock on node 2. Resource temporarily unavailable
Dec 22 11:45:19 node<<1>> gps: : Unable to read clock on node 2. Resource temporarily unavailable
Dec 22 11:45:26 node<<1>> gps: : Unable to set clock on node 2. Resource temporarily unavailableInterrupted function call
Dec 22 11:45:50 node<<1>> gps: : Unable to set clock on node 2. Resource temporarily unavailableInterrupted function callInterrupted function call
Dec 22 11:46:51 node<<1>> gps: : time increase in gps of 1356176819 s.
Dec 22 11:47:02 node<<2>> acquire2: : fast data recording off
Dec 22 11:47:02 node<<2>> acquire2: : integrated data recording off
Dec 26 17:10:47 node<<2>> acquire2: : fast data recording off
Dec 26 17:10:47 node<<2>> acquire2: : integrated data recording off
Dec 26 17:11:10 node<<1>> gps: : Unable to set clock on node 2. Interrupted function call
Dec 26 17:17:01 node<<2>> acquire2: : fast data recording off
Dec 26 17:17:01 node<<2>> acquire2: : integrated data recording off
Dec 29 11:33:32 node<<1>> gps: : nmea code too short with 64 chars.
Dec 29 11:33:33 node<<1>> gps: : invalid gps time
Dec 29 11:33:34 node<<1>> gps: : time increase in gps of 1356780815 s.
Dec 29 11:33:37 node<<2>> acquire2: : fast data recording off
Dec 29 11:33:37 node<<2>> acquire2: : integrated data recording off
Dec 26 17:10:47 node<<2>> acquire2: : fast data recording off
Dec 26 17:10:47 node<<2>> acquire2: : integrated data recording off
Dec 26 17:11:10 node<<1>> gps: : Unable to set clock on node 2. Interrupted function call
Dec 26 17:17:01 node<<2>> acquire2: : fast data recording off
Dec 26 17:17:01 node<<2>> acquire2: : integrated data recording off
Dec 28 02:34:13 node<<1>> gps: : time increase in gps of 1356662055 s.
Dec 28 02:34:18 node<<2>> acquire2: : fast data recording off
Dec 28 02:34:18 node<<2>> acquire2: : integrated data recording off
Dec 28 02:47:09 node<<1>> gps: : nmea code too short with 11 chars.
Dec 28 02:47:09 node<<1>> gps: : invalid gps time
Dec 28 02:47:10 node<<1>> gps: : time increase in gps of 1356662831 s.
Dec 28 02:47:13 node<<2>> acquire2: : fast data recording off
Dec 28 02:47:13 node<<2>> acquire2: : integrated data recording off
Dec 28 12:21:56 node<<2>> acquire2: : fast data recording off
Dec 28 12:21:56 node<<2>> acquire2: : integrated data recording off
Dec 28 12:32:08 node<<2>> acquire2: : fast data recording off
Dec 28 12:32:08 node<<2>> acquire2: : integrated data recording off
Dec 28 12:40:31 node<<1>> gps: : time increase in gps of 1356698433 s.
Dec 28 12:40:36 node<<2>> acquire2: : fast data recording off
Dec 28 12:40:36 node<<2>> acquire2: : integrated data recording off
Dec 28 14:39:36 node<<1>> gps: : time increase in gps of 1356705577 s.
Dec 28 14:39:40 node<<2>> acquire2: : fast data recording off
Dec 28 14:39:40 node<<2>> acquire2: : integrated data recording off
Dec 28 15:58:10 node<<1>> gps: : nmea code too short with 44 chars.
Dec 28 15:58:10 node<<1>> gps: : invalid gps time
Dec 28 15:58:11 node<<1>> gps: : time increase in gps of 1356710292 s.
Dec 28 15:58:14 node<<2>> acquire2: : fast data recording off
Dec 28 15:58:14 node<<2>> acquire2: : integrated data recording off
Dec 28 18:11:27 node<<1>> gps: : time increase in gps of 1356718288 s.
Dec 28 18:11:31 node<<2>> acquire2: : fast data recording off
Dec 28 18:11:31 node<<2>> acquire2: : integrated data recording off
