Dec  3 16:00:04 node<<1>> gps: : no interrupt or NMEA-input from gps receiver.
Dec  3 16:00:04 node<<1>> gps: : no interrupt or NMEA-input from gps receiver.
Dec  6 22:42:52 node<<1>> gps: : no interrupt or NMEA-input from gps receiver.
Dec  6 22:42:46 node<<1>> gps: : no interrupt or NMEA-input from gps receiver.
Dec 11 14:00:06 node<<1>> gps: : no interrupt or NMEA-input from gps receiver.
Dec 14 12:00:05 node<<1>> gps: : no interrupt or NMEA-input from gps receiver.
Dec 21 18:31:51 node<<2>> cdt: open_shmem2: open failed on shared memory for fbuffer
Dec 21 18:31:51 node<<2>> cdt: open_shmem2: calling process was killed
Dec 21 19:09:27 node<<2>> cdt: open_shmem2: open failed on shared memory for fbuffer
Dec 21 19:09:27 node<<2>> cdt: open_shmem2: calling process was killed
Dec 21 20:34:31 node<<1>> gps: : no interrupt or NMEA-input from gps receiver.
Dec 21 20:34:12 node<<1>> gps: : no interrupt or NMEA-input from gps receiver.
Dec 22 11:45:26 node<<1>> gps: : no interrupt or NMEA-input from gps receiver.
Dec 22 11:45:50 node<<1>> last message repeated 2 times
Dec 26 17:11:10 node<<1>> gps: : no interrupt or NMEA-input from gps receiver.
Dec 29 04:07:25 node<<1>> sst_status: : open failed on shared memory for ephemer in open_shmem1
Dec 26 17:11:10 node<<1>> gps: : no interrupt or NMEA-input from gps receiver.
