Dec  1 11:03:38 node<<2>> cdt: >>> start sending
Dec  1 11:03:38 node<<2>> cdt: connection established with Server
Dec  1 11:09:27 node<<2>> cdt: Broken Pipe 
Dec  1 11:09:27 node<<2>> cdt: cannot open connection with server
Dec  1 11:09:32 node<<2>> cdt: connection established with Server
Dec  1 15:33:11 node<<2>> cdt: >>> start sending
Dec  1 15:33:11 node<<2>> cdt: cannot get a socket to communicate
Dec  1 15:33:14 node<<2>> last message repeated 10827 times
Dec  1 15:33:14 node<<2>> cdt: connection established with Server
Dec  1 15:34:50 node<<2>> cdt: Broken Pipe 
Dec  1 15:34:50 node<<2>> cdt: cannot open connection with server
Dec  1 15:34:55 node<<2>> cdt: connection established with Server
Dec  1 11:22:58 node<<2>> cdt: >>> start sending
Dec  1 11:22:58 node<<2>> cdt: connection established with Server
Dec  1 11:26:16 node<<2>> cdt: Broken Pipe 
Dec  1 11:26:16 node<<2>> cdt: connection established with Server
Dec  2 10:53:00 node<<2>> cdt: >>> start sending
Dec  2 10:53:00 node<<2>> cdt: connection established with Server
Dec  2 11:08:14 node<<2>> cdt: Broken Pipe 
Dec  2 11:08:14 node<<2>> cdt: cannot open connection with server
Dec  2 11:08:19 node<<2>> cdt: connection established with Server
Dec  2 11:11:34 node<<2>> cdt: >>> start sending
Dec  2 11:11:34 node<<2>> cdt: connection established with Server
Dec  2 11:13:45 node<<2>> cdt: Broken Pipe 
Dec  2 11:13:45 node<<2>> cdt: cannot open connection with server
Dec  2 11:13:50 node<<2>> cdt: connection established with Server
Dec  3 10:54:43 node<<2>> cdt: >>> start sending
Dec  3 10:54:43 node<<2>> cdt: connection established with Server
Dec  3 11:08:49 node<<2>> cdt: Broken Pipe 
Dec  3 11:08:49 node<<2>> cdt: cannot open connection with server
Dec  3 11:08:54 node<<2>> cdt: connection established with Server
Dec  3 14:45:09 node<<2>> cdt: >>> start sending
Dec  3 14:45:09 node<<2>> cdt: connection established with Server
Dec  3 14:47:46 node<<2>> cdt: Broken Pipe 
Dec  3 14:47:46 node<<2>> cdt: cannot open connection with server
Dec  3 14:47:51 node<<2>> cdt: connection established with Server
Dec  3 11:28:50 node<<2>> cdt: >>> start sending
Dec  3 11:28:50 node<<2>> cdt: connection established with Server
Dec  3 11:32:07 node<<2>> cdt: Broken Pipe 
Dec  3 11:32:07 node<<2>> cdt: cannot open connection with server
Dec  3 11:32:12 node<<2>> cdt: connection established with Server
Dec  3 17:23:55 node<<2>> cdt: >>> start sending
Dec  3 17:23:55 node<<2>> cdt: connection established with Server
Dec  3 17:24:37 node<<2>> cdt: Broken Pipe 
Dec  3 17:24:37 node<<2>> cdt: connection established with Server
Dec  3 10:54:43 node<<2>> cdt: >>> start sending
Dec  3 10:54:43 node<<2>> cdt: connection established with Server
Dec  3 11:08:49 node<<2>> cdt: Broken Pipe 
Dec  3 11:08:49 node<<2>> cdt: cannot open connection with server
Dec  3 11:08:54 node<<2>> cdt: connection established with Server
Dec  3 14:45:09 node<<2>> cdt: >>> start sending
Dec  3 14:45:09 node<<2>> cdt: connection established with Server
Dec  3 14:47:46 node<<2>> cdt: Broken Pipe 
Dec  3 14:47:46 node<<2>> cdt: cannot open connection with server
Dec  3 14:47:51 node<<2>> cdt: connection established with Server
Dec  3 11:28:50 node<<2>> cdt: >>> start sending
Dec  3 11:28:50 node<<2>> cdt: connection established with Server
Dec  3 11:32:07 node<<2>> cdt: Broken Pipe 
Dec  3 11:32:07 node<<2>> cdt: cannot open connection with server
Dec  3 11:32:12 node<<2>> cdt: connection established with Server
Dec  3 17:23:55 node<<2>> cdt: >>> start sending
Dec  3 17:23:55 node<<2>> cdt: connection established with Server
Dec  3 17:24:37 node<<2>> cdt: Broken Pipe 
Dec  3 17:24:37 node<<2>> cdt: connection established with Server
Dec  4 10:51:55 node<<2>> cdt: >>> start sending
Dec  4 10:51:55 node<<2>> cdt: connection established with Server
Dec  4 11:06:11 node<<2>> cdt: Broken Pipe 
Dec  4 11:06:11 node<<2>> cdt: cannot open connection with server
Dec  4 11:06:16 node<<2>> cdt: connection established with Server
Dec  4 18:52:10 node<<2>> cdt: >>> start sending
Dec  4 18:52:10 node<<2>> cdt: connection established with Server
Dec  4 19:13:11 node<<2>> cdt: >>> start sending
Dec  4 19:13:11 node<<2>> cdt: connection established with Server
Dec  4 19:15:28 node<<2>> cdt: Broken Pipe 
Dec  4 19:15:28 node<<2>> cdt: connection established with Server
Dec  4 11:13:07 node<<2>> cdt: >>> start sending
Dec  4 11:13:07 node<<2>> cdt: connection established with Server
Dec  4 11:18:49 node<<2>> cdt: Broken Pipe 
Dec  4 11:18:49 node<<2>> cdt: cannot open connection with server
Dec  4 11:18:54 node<<2>> cdt: connection established with Server
Dec  5 10:50:59 node<<2>> cdt: >>> start sending
Dec  5 10:50:59 node<<2>> cdt: connection established with Server
Dec  5 11:08:53 node<<2>> cdt: Broken Pipe 
Dec  5 11:08:53 node<<2>> cdt: cannot open connection with server
Dec  5 11:08:58 node<<2>> cdt: connection established with Server
Dec  5 18:01:20 node<<2>> cdt: >>> start sending
Dec  5 18:01:21 node<<2>> cdt: connection established with Server
Dec  5 18:03:01 node<<2>> cdt: Broken Pipe 
Dec  5 18:03:01 node<<2>> cdt: cannot open connection with server
Dec  5 18:03:06 node<<2>> cdt: connection established with Server
Dec  5 11:24:36 node<<2>> cdt: >>> start sending
Dec  5 11:24:36 node<<2>> cdt: connection established with Server
Dec  5 11:29:42 node<<2>> cdt: >>> start sending
Dec  5 11:29:42 node<<2>> cdt: connection established with Server
Dec  5 14:46:24 node<<2>> cdt: >>> start sending
Dec  5 14:46:24 node<<2>> cdt: connection established with Server
Dec  5 18:46:31 node<<2>> cdt: Broken Pipe 
Dec  5 18:46:31 node<<2>> cdt: connection established with Server
Dec  5 18:58:01 node<<2>> cdt: >>> start sending
Dec  5 18:58:01 node<<2>> cdt: connection established with Server
Dec  5 18:59:13 node<<2>> cdt: Broken Pipe 
Dec  5 18:59:13 node<<2>> cdt: connection established with Server
Dec  6 10:53:10 node<<2>> cdt: >>> start sending
Dec  6 10:53:10 node<<2>> cdt: connection established with Server
Dec  6 11:15:11 node<<2>> cdt: Broken Pipe 
Dec  6 11:15:11 node<<2>> cdt: cannot open connection with server
Dec  6 11:15:16 node<<2>> cdt: connection established with Server
Dec  6 11:19:33 node<<2>> cdt: Broken Pipe 
Dec  6 11:19:33 node<<2>> cdt: connection established with Server
Dec  6 11:24:29 node<<2>> cdt: >>> start sending
Dec  6 11:24:29 node<<2>> cdt: connection established with Server
Dec  6 14:04:20 node<<2>> cdt: Broken Pipe 
Dec  6 14:04:20 node<<2>> cdt: connection established with Server
Dec  6 14:04:21 node<<2>> cdt: Broken Pipe 
Dec  6 14:04:21 node<<2>> cdt: connection established with Server
Dec  6 16:59:12 node<<2>> cdt: >>> start sending
Dec  6 16:59:12 node<<2>> cdt: cannot get a socket to communicate
Dec  6 16:59:15 node<<2>> last message repeated 10149 times
Dec  6 16:59:15 node<<2>> cdt: connection established with Server
Dec  6 17:00:58 node<<2>> cdt: Broken Pipe 
Dec  6 17:00:58 node<<2>> cdt: connection established with Server
Dec  6 22:43:04 node<<2>> cdt: Incomplete transmission with server 
Dec  7 10:44:34 node<<2>> cdt: >>> start sending
Dec  7 10:44:34 node<<2>> cdt: connection established with Server
Dec  7 10:50:45 node<<2>> cdt: Broken Pipe 
Dec  7 10:50:45 node<<2>> cdt: connection established with Server
Dec  7 11:41:27 node<<2>> cdt: >>> start sending
Dec  7 11:41:27 node<<2>> cdt: connection established with Server
Dec  7 11:43:27 node<<2>> cdt: Broken Pipe 
Dec  7 11:43:27 node<<2>> cdt: connection established with Server
Dec  7 11:43:56 node<<2>> cdt: Broken Pipe 
Dec  7 11:43:56 node<<2>> cdt: connection established with Server
Dec  7 11:43:57 node<<2>> cdt: Broken Pipe 
Dec  7 11:43:57 node<<2>> cdt: connection established with Server
Dec  7 11:43:57 node<<2>> cdt: Broken Pipe 
Dec  7 11:43:57 node<<2>> cdt: connection established with Server
Dec  7 11:48:33 node<<2>> cdt: Broken Pipe 
Dec  7 11:48:33 node<<2>> cdt: cannot open connection with server
Dec  7 11:48:38 node<<2>> cdt: cannot open connection with server
Dec  7 11:48:43 node<<2>> cdt: connection established with Server
Dec  7 11:51:34 node<<2>> cdt: Broken Pipe 
Dec  7 11:51:34 node<<2>> cdt: connection established with Server
Dec  7 21:53:54 node<<2>> cdt: >>> start sending
Dec  7 21:53:54 node<<2>> cdt: cannot get a socket to communicate
Dec  7 21:53:57 node<<2>> last message repeated 13483 times
Dec  7 21:53:57 node<<2>> cdt: connection established with Server
Dec  8 11:18:48 node<<2>> cdt: >>> start sending
Dec  8 11:18:48 node<<2>> cdt: connection established with Server
Dec  8 11:22:20 node<<2>> cdt: >>> start sending
Dec  8 11:22:20 node<<2>> cdt: connection established with Server
Dec  8 11:23:41 node<<2>> cdt: Broken Pipe 
Dec  8 11:23:41 node<<2>> cdt: cannot open connection with server
Dec  8 11:23:46 node<<2>> cdt: connection established with Server
Dec  8 14:25:33 node<<2>> cdt: >>> start sending
Dec  8 14:25:33 node<<2>> cdt: connection established with Server
Dec  8 14:28:22 node<<2>> cdt: Broken Pipe 
Dec  8 14:28:22 node<<2>> cdt: connection established with Server
Dec  8 17:44:57 node<<2>> cdt: >>> start sending
Dec  8 17:44:57 node<<2>> cdt: connection established with Server
Dec  8 17:51:18 node<<2>> cdt: Broken Pipe 
Dec  8 17:51:18 node<<2>> cdt: connection established with Server
Dec  8 11:33:17 node<<2>> cdt: >>> start sending
Dec  8 11:33:17 node<<2>> cdt: cannot get a socket to communicate
Dec  8 11:33:20 node<<2>> last message repeated 12421 times
Dec  8 11:33:20 node<<2>> cdt: connection established with Server
Dec  8 11:35:23 node<<2>> cdt: Broken Pipe 
Dec  8 11:35:23 node<<2>> cdt: cannot open connection with server
Dec  8 11:35:28 node<<2>> cdt: connection established with Server
Dec  8 11:35:39 node<<2>> cdt: Broken Pipe 
Dec  8 11:35:39 node<<2>> cdt: connection established with Server
Dec  8 20:13:10 node<<2>> cdt: Broken Pipe 
Dec  8 20:13:10 node<<2>> cdt: connection established with Server
Dec  8 20:53:48 node<<2>> cdt: >>> start sending
Dec  8 20:53:48 node<<2>> cdt: connection established with Server
Dec  8 20:55:01 node<<2>> cdt: Broken Pipe 
Dec  8 20:55:01 node<<2>> cdt: connection established with Server
Dec  9 11:28:59 node<<2>> cdt: >>> start sending
Dec  9 11:28:59 node<<2>> cdt: connection established with Server
Dec  9 11:29:48 node<<2>> cdt: Broken Pipe 
Dec  9 11:29:48 node<<2>> cdt: cannot open connection with server
Dec  9 11:29:53 node<<2>> cdt: connection established with Server
Dec  9 11:38:44 node<<2>> cdt: Broken Pipe 
Dec  9 11:38:44 node<<2>> cdt: connection established with Server
Dec  9 11:02:12 node<<2>> cdt: >>> start sending
Dec  9 11:02:12 node<<2>> cdt: connection established with Server
Dec  9 11:05:40 node<<2>> cdt: Broken Pipe 
Dec  9 11:05:40 node<<2>> cdt: connection established with Server
Dec  9 14:13:49 node<<2>> cdt: >>> start sending
Dec  9 14:13:49 node<<2>> cdt: connection established with Server
Dec  9 19:19:02 node<<2>> cdt: >>> start sending
Dec  9 19:19:08 node<<2>> cdt: connection established with Server
Dec  9 19:19:26 node<<2>> cdt: Broken Pipe 
Dec  9 19:19:26 node<<2>> cdt: connection established with Server
Dec  9 21:57:02 node<<2>> cdt: >>> start sending
Dec  9 21:57:02 node<<2>> cdt: connection established with Server
Dec  8 11:18:48 node<<2>> cdt: >>> start sending
Dec  8 11:18:48 node<<2>> cdt: connection established with Server
Dec  8 11:22:20 node<<2>> cdt: >>> start sending
Dec  8 11:22:20 node<<2>> cdt: connection established with Server
Dec  8 11:23:41 node<<2>> cdt: Broken Pipe 
Dec  8 11:23:41 node<<2>> cdt: cannot open connection with server
Dec  8 11:23:46 node<<2>> cdt: connection established with Server
Dec  8 14:25:33 node<<2>> cdt: >>> start sending
Dec  8 14:25:33 node<<2>> cdt: connection established with Server
Dec  8 14:28:22 node<<2>> cdt: Broken Pipe 
Dec  8 14:28:22 node<<2>> cdt: connection established with Server
Dec  8 17:44:57 node<<2>> cdt: >>> start sending
Dec  8 17:44:57 node<<2>> cdt: connection established with Server
Dec  8 17:51:18 node<<2>> cdt: Broken Pipe 
Dec  8 17:51:18 node<<2>> cdt: connection established with Server
Dec  8 11:33:17 node<<2>> cdt: >>> start sending
Dec  8 11:33:17 node<<2>> cdt: cannot get a socket to communicate
Dec  8 11:33:20 node<<2>> last message repeated 12421 times
Dec  8 11:33:20 node<<2>> cdt: connection established with Server
Dec  8 11:35:23 node<<2>> cdt: Broken Pipe 
Dec  8 11:35:23 node<<2>> cdt: cannot open connection with server
Dec  8 11:35:28 node<<2>> cdt: connection established with Server
Dec  8 11:35:39 node<<2>> cdt: Broken Pipe 
Dec  8 11:35:39 node<<2>> cdt: connection established with Server
Dec  8 20:13:10 node<<2>> cdt: Broken Pipe 
Dec  8 20:13:10 node<<2>> cdt: connection established with Server
Dec  8 20:53:48 node<<2>> cdt: >>> start sending
Dec  8 20:53:48 node<<2>> cdt: connection established with Server
Dec  8 20:55:01 node<<2>> cdt: Broken Pipe 
Dec  8 20:55:01 node<<2>> cdt: connection established with Server
Dec  8 11:18:48 node<<2>> cdt: >>> start sending
Dec  8 11:18:48 node<<2>> cdt: connection established with Server
Dec  8 11:22:20 node<<2>> cdt: >>> start sending
Dec  8 11:22:20 node<<2>> cdt: connection established with Server
Dec  8 11:23:41 node<<2>> cdt: Broken Pipe 
Dec  8 11:23:41 node<<2>> cdt: cannot open connection with server
Dec  8 11:23:46 node<<2>> cdt: connection established with Server
Dec  8 14:25:33 node<<2>> cdt: >>> start sending
Dec  8 14:25:33 node<<2>> cdt: connection established with Server
Dec  8 14:28:22 node<<2>> cdt: Broken Pipe 
Dec  8 14:28:22 node<<2>> cdt: connection established with Server
Dec  8 17:44:57 node<<2>> cdt: >>> start sending
Dec  8 17:44:57 node<<2>> cdt: connection established with Server
Dec  8 17:51:18 node<<2>> cdt: Broken Pipe 
Dec  8 17:51:18 node<<2>> cdt: connection established with Server
Dec  8 11:33:17 node<<2>> cdt: >>> start sending
Dec  8 11:33:17 node<<2>> cdt: cannot get a socket to communicate
Dec  8 11:33:20 node<<2>> last message repeated 12421 times
Dec  8 11:33:20 node<<2>> cdt: connection established with Server
Dec  8 11:35:23 node<<2>> cdt: Broken Pipe 
Dec  8 11:35:23 node<<2>> cdt: cannot open connection with server
Dec  8 11:35:28 node<<2>> cdt: connection established with Server
Dec  8 11:35:39 node<<2>> cdt: Broken Pipe 
Dec  8 11:35:39 node<<2>> cdt: connection established with Server
Dec  8 20:13:10 node<<2>> cdt: Broken Pipe 
Dec  8 20:13:10 node<<2>> cdt: connection established with Server
Dec  8 20:53:48 node<<2>> cdt: >>> start sending
Dec  8 20:53:48 node<<2>> cdt: connection established with Server
Dec  8 20:55:01 node<<2>> cdt: Broken Pipe 
Dec  8 20:55:01 node<<2>> cdt: connection established with Server
Dec  9 11:28:59 node<<2>> cdt: >>> start sending
Dec  9 11:28:59 node<<2>> cdt: connection established with Server
Dec  9 11:29:48 node<<2>> cdt: Broken Pipe 
Dec  9 11:29:48 node<<2>> cdt: cannot open connection with server
Dec  9 11:29:53 node<<2>> cdt: connection established with Server
Dec  9 11:38:44 node<<2>> cdt: Broken Pipe 
Dec  9 11:38:44 node<<2>> cdt: connection established with Server
Dec  9 11:02:12 node<<2>> cdt: >>> start sending
Dec  9 11:02:12 node<<2>> cdt: connection established with Server
Dec  9 11:05:40 node<<2>> cdt: Broken Pipe 
Dec  9 11:05:40 node<<2>> cdt: connection established with Server
Dec  9 14:13:49 node<<2>> cdt: >>> start sending
Dec  9 14:13:49 node<<2>> cdt: connection established with Server
Dec  9 19:19:02 node<<2>> cdt: >>> start sending
Dec  9 19:19:08 node<<2>> cdt: connection established with Server
Dec  9 19:19:26 node<<2>> cdt: Broken Pipe 
Dec  9 19:19:26 node<<2>> cdt: connection established with Server
Dec  9 21:57:02 node<<2>> cdt: >>> start sending
Dec  9 21:57:02 node<<2>> cdt: connection established with Server
Dec 10 11:34:50 node<<2>> cdt: >>> start sending
Dec 10 11:34:50 node<<2>> cdt: connection established with Server
Dec 10 11:36:54 node<<2>> cdt: Broken Pipe 
Dec 10 11:36:54 node<<2>> cdt: cannot open connection with server
Dec 10 11:36:59 node<<2>> cdt: connection established with Server
Dec 10 11:16:05 node<<2>> cdt: >>> start sending
Dec 10 11:16:05 node<<2>> cdt: connection established with Server
Dec 10 11:19:30 node<<2>> cdt: Broken Pipe 
Dec 10 11:19:30 node<<2>> cdt: connection established with Server
Dec 10 14:45:03 node<<2>> cdt: >>> start sending
Dec 10 14:45:03 node<<2>> cdt: connection established with Server
Dec 10 14:45:43 node<<2>> cdt: Broken Pipe 
Dec 10 14:45:43 node<<2>> cdt: connection established with Server
Dec 10 17:16:47 node<<2>> cdt: >>> start sending
Dec 10 17:16:47 node<<2>> cdt: connection established with Server
Dec 10 17:17:57 node<<2>> cdt: Broken Pipe 
Dec 10 17:17:57 node<<2>> cdt: connection established with Server
Dec  5 10:50:59 node<<2>> cdt: >>> start sending
Dec  5 10:50:59 node<<2>> cdt: connection established with Server
Dec  5 11:08:53 node<<2>> cdt: Broken Pipe 
Dec  5 11:08:53 node<<2>> cdt: cannot open connection with server
Dec  5 11:08:58 node<<2>> cdt: connection established with Server
Dec  5 18:01:20 node<<2>> cdt: >>> start sending
Dec  5 18:01:21 node<<2>> cdt: connection established with Server
Dec  5 18:03:01 node<<2>> cdt: Broken Pipe 
Dec  5 18:03:01 node<<2>> cdt: cannot open connection with server
Dec  5 18:03:06 node<<2>> cdt: connection established with Server
Dec  5 11:24:36 node<<2>> cdt: >>> start sending
Dec  5 11:24:36 node<<2>> cdt: connection established with Server
Dec  5 11:29:42 node<<2>> cdt: >>> start sending
Dec  5 11:29:42 node<<2>> cdt: connection established with Server
Dec  5 14:46:24 node<<2>> cdt: >>> start sending
Dec  5 14:46:24 node<<2>> cdt: connection established with Server
Dec  5 18:46:31 node<<2>> cdt: Broken Pipe 
Dec  5 18:46:31 node<<2>> cdt: connection established with Server
Dec  5 18:58:01 node<<2>> cdt: >>> start sending
Dec  5 18:58:01 node<<2>> cdt: connection established with Server
Dec  5 18:59:13 node<<2>> cdt: Broken Pipe 
Dec  5 18:59:13 node<<2>> cdt: connection established with Server
Dec 11 11:30:23 node<<2>> cdt: >>> start sending
Dec 11 11:30:23 node<<2>> cdt: connection established with Server
Dec 11 11:38:22 node<<2>> cdt: Broken Pipe 
Dec 11 11:38:22 node<<2>> cdt: cannot open connection with server
Dec 11 11:38:27 node<<2>> cdt: connection established with Server
Dec 11 11:07:56 node<<2>> cdt: >>> start sending
Dec 11 11:07:56 node<<2>> cdt: connection established with Server
Dec 11 11:10:12 node<<2>> cdt: Broken Pipe 
Dec 11 11:10:12 node<<2>> cdt: connection established with Server
Dec 12 11:34:47 node<<2>> cdt: >>> start sending
Dec 12 11:34:47 node<<2>> cdt: connection established with Server
Dec 12 11:39:15 node<<2>> cdt: Broken Pipe 
Dec 12 11:39:15 node<<2>> cdt: cannot open connection with server
Dec 12 11:39:20 node<<2>> cdt: connection established with Server
Dec 12 11:20:01 node<<2>> cdt: >>> start sending
Dec 12 11:20:01 node<<2>> cdt: connection established with Server
Dec 12 11:22:43 node<<2>> cdt: Broken Pipe 
Dec 12 11:22:43 node<<2>> cdt: cannot open connection with server
Dec 12 11:22:48 node<<2>> cdt: connection established with Server
Dec 12 19:32:56 node<<2>> cdt: Broken Pipe 
Dec 12 19:32:56 node<<2>> cdt: connection established with Server
Dec 12 22:27:13 node<<2>> cdt: >>> start sending
Dec 12 22:27:13 node<<2>> cdt: connection established with Server
Dec 13 11:01:06 node<<2>> cdt: >>> start sending
Dec 13 11:01:06 node<<2>> cdt: connection established with Server
Dec 13 11:02:39 node<<2>> cdt: Broken Pipe 
Dec 13 11:02:39 node<<2>> cdt: cannot open connection with server
Dec 13 11:02:44 node<<2>> cdt: connection established with Server
Dec 13 14:50:11 node<<2>> cdt: >>> start sending
Dec 13 14:50:11 node<<2>> cdt: connection established with Server
Dec 13 14:52:07 node<<2>> cdt: Broken Pipe 
Dec 13 14:52:07 node<<2>> cdt: connection established with Server
Dec 13 19:04:43 node<<2>> cdt: >>> start sending
Dec 13 19:04:43 node<<2>> cdt: connection established with Server
Dec 13 19:05:09 node<<2>> cdt: Broken Pipe 
Dec 13 19:05:09 node<<2>> cdt: connection established with Server
Dec 13 19:05:09 node<<2>> cdt: Broken Pipe 
Dec 13 19:05:09 node<<2>> cdt: connection established with Server
Dec 13 13:51:55 node<<2>> cdt: >>> start sending
Dec 13 13:51:55 node<<2>> cdt: connection established with Server
Dec 13 14:47:27 node<<2>> cdt: >>> start sending
Dec 13 14:47:27 node<<2>> cdt: connection established with Server
Dec 13 14:47:53 node<<2>> cdt: Broken Pipe 
Dec 13 14:47:53 node<<2>> cdt: connection established with Server
Dec 13 15:27:09 node<<2>> cdt: >>> start sending
Dec 13 15:27:09 node<<2>> cdt: connection established with Server
Dec 13 22:29:42 node<<2>> cdt: >>> start sending
Dec 13 22:29:42 node<<2>> cdt: cannot get a socket to communicate
Dec 13 22:29:44 node<<2>> last message repeated 7400 times
Dec 13 22:29:44 node<<2>> cdt: connection established with Server
Dec 13 22:32:26 node<<2>> cdt: >>> start sending
Dec 13 22:32:26 node<<2>> cdt: connection established with Server
Dec 13 22:33:18 node<<2>> cdt: >>> start sending
Dec 13 22:33:18 node<<2>> cdt: connection established with Server
Dec 13 22:40:12 node<<2>> cdt: >>> start sending
Dec 13 22:40:12 node<<2>> cdt: connection established with Server
Dec 13 22:42:13 node<<2>> cdt: Broken Pipe 
Dec 13 22:42:13 node<<2>> cdt: connection established with Server
Dec 13 22:42:14 node<<2>> cdt: Broken Pipe 
Dec 13 22:42:14 node<<2>> cdt: connection established with Server
Dec 14 10:15:44 node<<2>> cdt: >>> start sending
Dec 14 10:15:44 node<<2>> cdt: connection established with Server
Dec 14 11:09:37 node<<2>> cdt: >>> start sending
Dec 14 11:09:37 node<<2>> cdt: connection established with Server
Dec 14 11:10:27 node<<2>> cdt: Broken Pipe 
Dec 14 11:10:27 node<<2>> cdt: cannot open connection with server
Dec 14 11:10:32 node<<2>> cdt: connection established with Server
Dec 14 19:22:19 node<<2>> cdt: >>> start sending
Dec 14 19:22:19 node<<2>> cdt: connection established with Server
Dec 14 19:22:47 node<<2>> cdt: Broken Pipe 
Dec 14 19:22:47 node<<2>> cdt: connection established with Server
Dec 14 20:00:34 node<<2>> cdt: >>> start sending
Dec 14 20:00:34 node<<2>> cdt: connection established with Server
Dec 14 20:01:38 node<<2>> cdt: Broken Pipe 
Dec 14 20:01:38 node<<2>> cdt: connection established with Server
Dec 14 20:18:50 node<<2>> cdt: >>> start sending
Dec 14 20:18:50 node<<2>> cdt: connection established with Server
Dec 14 20:19:46 node<<2>> cdt: Broken Pipe 
Dec 14 20:19:46 node<<2>> cdt: connection established with Server
Dec 14 02:12:55 node<<2>> cdt: >>> start sending
Dec 14 02:12:55 node<<2>> cdt: connection established with Server
Dec 14 11:35:31 node<<2>> cdt: >>> start sending
Dec 14 11:35:31 node<<2>> cdt: connection established with Server
Dec 14 11:55:37 node<<2>> cdt: Broken Pipe 
Dec 14 11:55:37 node<<2>> cdt: connection established with Server
Dec 14 12:47:46 node<<2>> cdt: >>> start sending
Dec 14 12:47:46 node<<2>> cdt: connection established with Server
Dec 14 12:48:38 node<<2>> cdt: >>> start sending
Dec 14 12:48:38 node<<2>> cdt: connection established with Server
Dec 14 12:48:50 node<<2>> cdt: Broken Pipe 
Dec 14 12:48:50 node<<2>> cdt: connection established with Server
Dec 14 16:37:50 node<<2>> cdt: Broken Pipe 
Dec 14 16:37:50 node<<2>> cdt: cannot get a socket to communicate
Dec 14 16:38:20 node<<2>> last message repeated 118001 times
Dec 14 16:41:51 node<<2>> cdt: >>> start sending
Dec 14 16:41:51 node<<2>> cdt: connection established with Server
Dec 14 16:43:52 node<<2>> cdt: Broken Pipe 
Dec 14 16:43:52 node<<2>> cdt: connection established with Server
Dec 27 03:15:13 node<<2>> cdt: >>> start sending
Dec 27 03:15:13 node<<2>> cdt: connection established with Server
Dec 27 03:16:40 node<<2>> cdt: >>> start sending
Dec 27 03:16:40 node<<2>> cdt: connection established with Server
Dec 27 12:22:08 node<<2>> cdt: >>> start sending
Dec 27 12:22:08 node<<2>> cdt: connection established with Server
Dec 27 12:24:04 node<<2>> cdt: Broken Pipe 
Dec 27 12:24:04 node<<2>> cdt: connection established with Server
Dec 21 18:31:51 node<<2>> cdt: >>> start sending
Dec 21 18:31:51 node<<2>> cdt: Aborted 
Dec 21 19:09:27 node<<2>> cdt: >>> start sending
Dec 21 19:09:27 node<<2>> cdt: Aborted 
Dec 21 19:30:29 node<<2>> cdt: >>> start sending
Dec 21 19:30:29 node<<2>> cdt: connection established with Server
Dec 21 19:32:16 node<<2>> cdt: Broken Pipe 
Dec 21 19:32:16 node<<2>> cdt: connection established with Server
Dec 21 20:31:09 node<<2>> cdt: >>> start sending
Dec 21 20:31:09 node<<2>> cdt: connection established with Server
Dec 21 20:34:04 node<<2>> cdt: >>> start sending
Dec 21 20:34:14 node<<2>> cdt: cannot open connection with server
Dec 21 20:35:38 node<<2>> cdt: >>> start sending
Dec 21 20:35:44 node<<2>> cdt: connection established with Server
Dec 21 20:39:00 node<<2>> cdt: Broken Pipe 
Dec 21 20:39:00 node<<2>> cdt: connection established with Server
Dec 22 11:45:10 node<<2>> cdt: >>> start sending
Dec 22 11:45:10 node<<2>> cdt: connection established with Server
Dec 22 11:45:37 node<<2>> cdt: Incomplete transmission with server 
Dec 22 11:47:02 node<<2>> cdt: >>> start sending
Dec 22 11:47:02 node<<2>> cdt: connection established with Server
Dec 22 11:50:03 node<<2>> cdt: Broken Pipe 
Dec 22 11:50:03 node<<2>> cdt: connection established with Server
Dec 26 17:10:47 node<<2>> cdt: >>> start sending
Dec 26 17:10:47 node<<2>> cdt: connection established with Server
Dec 26 17:11:25 node<<2>> cdt: Incomplete transmission with server 
Dec 26 17:17:01 node<<2>> cdt: >>> start sending
Dec 26 17:17:07 node<<2>> cdt: connection established with Server
Dec 26 17:42:37 node<<2>> cdt: Broken Pipe 
Dec 26 17:42:37 node<<2>> cdt: connection established with Server
Dec 26 17:51:34 node<<2>> cdt: Broken Pipe 
Dec 26 17:51:34 node<<2>> cdt: connection established with Server
Dec 26 17:57:58 node<<2>> cdt: Broken Pipe 
Dec 26 17:57:58 node<<2>> cdt: connection established with Server
Dec 26 18:29:05 node<<2>> cdt: Broken Pipe 
Dec 26 18:29:05 node<<2>> cdt: connection established with Server
Dec 29 11:33:37 node<<2>> cdt: >>> start sending
Dec 29 11:33:37 node<<2>> cdt: connection established with Server
Dec 29 11:35:01 node<<2>> cdt: Broken Pipe 
Dec 29 11:35:01 node<<2>> cdt: connection established with Server
Dec 29 11:56:11 node<<2>> cdt: Broken Pipe 
Dec 29 11:56:11 node<<2>> cdt: connection established with Server
Dec 29 11:57:48 node<<2>> cdt: Broken Pipe 
Dec 29 11:57:48 node<<2>> cdt: connection established with Server
Dec 26 17:10:47 node<<2>> cdt: >>> start sending
Dec 26 17:10:47 node<<2>> cdt: connection established with Server
Dec 26 17:11:25 node<<2>> cdt: Incomplete transmission with server 
Dec 26 17:17:01 node<<2>> cdt: >>> start sending
Dec 26 17:17:07 node<<2>> cdt: connection established with Server
Dec 26 17:42:37 node<<2>> cdt: Broken Pipe 
Dec 26 17:42:37 node<<2>> cdt: connection established with Server
Dec 26 17:51:34 node<<2>> cdt: Broken Pipe 
Dec 26 17:51:34 node<<2>> cdt: connection established with Server
Dec 26 17:57:58 node<<2>> cdt: Broken Pipe 
Dec 26 17:57:58 node<<2>> cdt: connection established with Server
Dec 26 18:29:05 node<<2>> cdt: Broken Pipe 
Dec 26 18:29:05 node<<2>> cdt: connection established with Server
Dec 28 02:34:18 node<<2>> cdt: >>> start sending
Dec 28 02:34:18 node<<2>> cdt: connection established with Server
Dec 28 02:47:13 node<<2>> cdt: >>> start sending
Dec 28 02:47:13 node<<2>> cdt: connection established with Server
Dec 28 12:21:56 node<<2>> cdt: >>> start sending
Dec 28 12:21:56 node<<2>> cdt: connection established with Server
Dec 28 12:32:08 node<<2>> cdt: >>> start sending
Dec 28 12:32:14 node<<2>> cdt: connection established with Server
Dec 28 12:40:36 node<<2>> cdt: >>> start sending
Dec 28 12:40:36 node<<2>> cdt: connection established with Server
Dec 28 12:43:53 node<<2>> cdt: Broken Pipe 
Dec 28 12:43:53 node<<2>> cdt: connection established with Server
Dec 28 12:44:13 node<<2>> cdt: Broken Pipe 
Dec 28 12:44:13 node<<2>> cdt: connection established with Server
Dec 28 12:44:34 node<<2>> cdt: Broken Pipe 
Dec 28 12:44:34 node<<2>> cdt: connection established with Server
Dec 28 12:44:35 node<<2>> cdt: Broken Pipe 
Dec 28 12:44:35 node<<2>> cdt: connection established with Server
Dec 28 12:44:36 node<<2>> cdt: Broken Pipe 
Dec 28 12:44:36 node<<2>> cdt: connection established with Server
Dec 28 12:44:36 node<<2>> cdt: Broken Pipe 
Dec 28 12:44:36 node<<2>> cdt: connection established with Server
Dec 28 12:45:43 node<<2>> cdt: Broken Pipe 
Dec 28 12:45:43 node<<2>> cdt: connection established with Server
Dec 28 12:50:03 node<<2>> cdt: Broken Pipe 
Dec 28 12:50:03 node<<2>> cdt: connection established with Server
Dec 28 12:51:11 node<<2>> cdt: Broken Pipe 
Dec 28 12:51:11 node<<2>> cdt: connection established with Server
Dec 28 13:15:48 node<<2>> cdt: Broken Pipe 
Dec 28 13:15:48 node<<2>> cdt: connection established with Server
Dec 28 13:16:56 node<<2>> cdt: Broken Pipe 
Dec 28 13:16:56 node<<2>> cdt: connection established with Server
Dec 28 13:21:43 node<<2>> cdt: Broken Pipe 
Dec 28 13:21:43 node<<2>> cdt: connection established with Server
Dec 28 13:26:41 node<<2>> cdt: Broken Pipe 
Dec 28 13:26:41 node<<2>> cdt: connection established with Server
Dec 28 13:44:37 node<<2>> cdt: Broken Pipe 
Dec 28 13:44:37 node<<2>> cdt: connection established with Server
Dec 28 14:07:39 node<<2>> cdt: Broken Pipe 
Dec 28 14:07:39 node<<2>> cdt: cannot open connection with server
Dec 28 14:07:54 node<<2>> last message repeated 3 times
Dec 28 14:07:59 node<<2>> cdt: connection established with Server
Dec 28 14:33:01 node<<2>> cdt: Broken Pipe 
Dec 28 14:33:01 node<<2>> cdt: connection established with Server
Dec 28 14:33:33 node<<2>> cdt: Broken Pipe 
Dec 28 14:33:33 node<<2>> cdt: connection established with Server
Dec 28 14:33:34 node<<2>> cdt: Broken Pipe 
Dec 28 14:33:34 node<<2>> cdt: connection established with Server
Dec 28 14:33:34 node<<2>> cdt: Broken Pipe 
Dec 28 14:33:34 node<<2>> cdt: connection established with Server
Dec 28 14:39:40 node<<2>> cdt: >>> start sending
Dec 28 14:39:40 node<<2>> cdt: connection established with Server
Dec 28 15:34:28 node<<2>> cdt: Broken Pipe 
Dec 28 15:34:28 node<<2>> cdt: connection established with Server
Dec 28 15:58:14 node<<2>> cdt: >>> start sending
Dec 28 15:58:14 node<<2>> cdt: connection established with Server
Dec 28 17:04:06 node<<2>> cdt: Broken Pipe 
Dec 28 17:04:06 node<<2>> cdt: connection established with Server
Dec 28 18:04:37 node<<2>> cdt: Broken Pipe 
Dec 28 18:04:37 node<<2>> cdt: connection established with Server
Dec 28 18:04:39 node<<2>> cdt: Broken Pipe 
Dec 28 18:04:39 node<<2>> cdt: connection established with Server
Dec 28 18:05:43 node<<2>> cdt: Broken Pipe 
Dec 28 18:05:43 node<<2>> cdt: connection established with Server
Dec 28 18:11:31 node<<2>> cdt: >>> start sending
Dec 28 18:11:31 node<<2>> cdt: connection established with Server
Dec 28 18:14:22 node<<2>> cdt: Broken Pipe 
Dec 28 18:14:22 node<<2>> cdt: connection established with Server
Dec 28 18:23:29 node<<2>> cdt: Broken Pipe 
Dec 28 18:23:29 node<<2>> cdt: connection established with Server
